# Generated by Django 5.2.5 on 2025-11-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('staff', 'Staff'), ('approver_lvl1', 'Approver Level 1'), ('approver_lvl2', 'Approver Level 2'), ('finance', 'Finance')], default='staff', help_text='Determines the default permissions the user has in the system.', max_length=32),
        ),
    ]
