# Generated by Django 5.2.5 on 2025-11-20 17:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procurement_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentExtractionResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('proforma', 'Proforma'), ('po', 'Purchase Order'), ('receipt', 'Receipt')], max_length=20)),
                ('firebase_url', models.URLField()),
                ('raw_text', models.TextField(blank=True)),
                ('baseline_data', models.JSONField(blank=True, default=dict)),
                ('model_data', models.JSONField(blank=True, null=True)),
                ('final_data', models.JSONField(default=dict)),
                ('engine_used', models.CharField(default='baseline', max_length=64)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_results', to='procurement_app.purchaserequest')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ReceiptValidationResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_match', models.BooleanField(default=False)),
                ('score', models.FloatField(default=0.0)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_validation', to='procurement_app.purchaserequest')),
            ],
        ),
    ]
