# Generated by Django 5.2.5 on 2025-11-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement_app', '0003_purchaserequest_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='reference',
            field=models.CharField(blank=True, editable=False, max_length=32, unique=True),
        ),
    ]
